name: API Secret Demo

on:
  push:
    branches: [ main ]

jobs:
  demo-secret-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Print Secret (Demo Only)
      run: echo "Using API Key: ${{ secrets.MY_API_KEY }}"
